# Generated by Django 2.2.3 on 2019-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_upload', models.FileField(upload_to='uploads')),
                ('file_size_display', models.CharField(max_length=20)),
            ],
        ),
    ]
