# Generated by Django 2.2.3 on 2019-08-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
