# Generated by Django 2.2.3 on 2019-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size_display',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
