# Generated by Django 2.2.4 on 2019-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcode',
            name='heading',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
